[package]
name = "obj-pool"
version = "0.1.0"
authors = ["Artem Shein <sc-github@aisys.ru>", "Stjepan Glavina <stjepang@gmail.com>"]
description = "A simple object arena"
repository = "https://github.com/artemshein/obj-pool"
documentation = "https://docs.rs/obj-pool"
readme = "README.md"
license = "Apache-2.0/MIT"
categories = ["memory-management"]

[badges]
travis-ci = { repository = "artemshein/obj-pool" }

[dependencies]
unreachable = "0.1"
